version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/user/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build:
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - node-network
  proxy:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: proxy
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge